Repository react-pakistan/react-pakistan-docs, pull requests merged in 2019-10, with the labels that each got.

#2 Taimoor/docu setup
  .dockerignore
  Dockerfile
  docker-compose.yml
  docs/doc1.md
  docs/doc2.md
  docs/doc3.md
  docs/exampledoc4.md
  docs/exampledoc5.md
  website/README.md
  website/blog/2016-03-11-blog-post.md
  website/blog/2017-04-10-blog-post-two.md
  website/blog/2017-09-25-testing-rss.md
  website/blog/2017-09-26-adding-rss.md
  website/blog/2017-10-24-new-version-1.0.0.md
  website/core/Footer.js
  website/i18n/en.json
  website/package.json
  website/pages/en/help.js
  website/pages/en/index.js
  website/pages/en/users.js
  website/sidebars.json
  website/siteConfig.js
  website/static/css/custom.css
  website/static/img/favicon.ico
  website/static/img/oss_logo.png
  website/static/img/undraw_code_review.svg
  website/static/img/undraw_monitor.svg
  website/static/img/undraw_note_list.svg
  website/static/img/undraw_online.svg
  website/static/img/undraw_open_source.svg
  website/static/img/undraw_operating_system.svg
  website/static/img/undraw_react.svg
  website/static/img/undraw_tweetstorm.svg
  website/static/img/undraw_youtube_tutorial.svg
  website/yarn.lock
Labels: documentation

#3 :sparkles: added ci/cd config
  .github/workflows/ci-cd.yml
Labels: enhancement

#4 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#6 :sparkles: added libs and adjusted app layer
  docs/doc1.md
  docs/doc2.md
  docs/react-commons-collection.md
  docs/react-icon-collection.md
  docs/react-ui-collection.md
  website/i18n/en.json
  website/package.json
  website/pages/en/index.js
  website/siteConfig.js
  website/yarn.lock
Labels: documentation, enhancement

#7 :recycle: updated CI
  .github/workflows/ci-cd.yml
Labels: bug

#10 Adding documentation to react-commons-collection.md
  docs/react-commons-collection.md
  package-lock.json
  website/package-lock.json
Labels: documentation

#11 Taimoor/amends
  docs/exampledoc4.md
  docs/exampledoc5.md
  docs/react-commons-collection.md
  docs/react-icon-collection.md
  docs/react-logo-collection.md
  docs/react-native-boilerplate.md
  docs/react-ui-collection.md
  package-lock.json
  website/i18n/en.json
  website/package-lock.json
  website/pages/en/index.js
  website/sidebars.json
  website/siteConfig.js
Labels: enhancement

#13 adding documentation for icon and ui whilst design consistent on all …
  docs/react-commons-collection.md
  docs/react-icon-collection.md
  docs/react-ui-collection.md
  website/i18n/en.json
Labels: documentation

#14 Taimoor/amends
  .DS_Store
  website/.DS_Store
  website/core/Footer.js
  website/i18n/en.json
  website/pages/en/index.js
  website/static/.DS_Store
  website/static/img/react-commons.svg
  website/static/img/react-design.svg
  website/static/img/react-icon.svg
  website/static/img/react-logo.svg
  website/static/img/react-native.svg
  website/static/img/react-pakistan.svg
  website/static/img/react-ui.svg
Labels: enhancement

#15 :recycle: added contributors for react commons
  docs/react-commons-contributors.md
  docs/react-docs-contributors.md
  docs/react-icon-contributors.md
  docs/react-logo-contributors.md
  docs/react-native-contributors.md
  docs/react-ui-contributors.md
  website/i18n/en.json
  website/sidebars.json
Labels: documentation

#16 :recycle: necessary amends
  .gitignore
  docs/react-commons-contributors.md
  docs/react-docs-contributors.md
  docs/react-icon-contributors.md
  docs/react-logo-contributors.md
  docs/react-native-contributors.md
  docs/react-ui-contributors.md
  website/core/Footer.js
  website/pages/en/index.js
  website/siteConfig.js
Labels: enhancement

#17 :recycle: updated react commons README
  docs/react-commons-collection.md
  website/siteConfig.js
Labels: documentation

#18 :recycle: upgraded depedencies
  website/yarn.lock
Labels: documentation

#19 Taimoor/amends
  website/package.json
Labels: enhancement

#20 :updated project logo and favicon
  .DS_Store
  .gitignore
  website/.DS_Store
  website/siteConfig.js
  website/static/.DS_Store
  website/static/img/favicon.ico
  website/static/img/oss_logo.png
  website/static/img/react-pakistan-logo-white.svg
  website/static/img/react-pakistan-logo.svg
  website/static/img/undraw_code_review.svg
  website/static/img/undraw_monitor.svg
  website/static/img/undraw_note_list.svg
  website/static/img/undraw_online.svg
  website/static/img/undraw_open_source.svg
  website/static/img/undraw_operating_system.svg
  website/static/img/undraw_react.svg
  website/static/img/undraw_tweetstorm.svg
  website/static/img/undraw_youtube_tutorial.svg
Labels: enhancement

#21 Taimoor/amends
  docs/react-icon-collection.md
  docs/react-ui-collection.md
Labels: enhancement

#22 :recycle: search api hooked
  website/i18n/en.json
  website/package.json
  website/pages/en/index.js
  website/siteConfig.js
  website/yarn.lock
Labels: enhancement

#23 :recycle: updated Icon docs
  docs/react-icon-collection.md
Labels: documentation

#24 :recycle: added logo docs
  docs/react-icon-collection.md
  docs/react-logo-collection.md
Labels: documentation

#25 :recycle: added React Native docs
  docs/react-native-boilerplate.md
Labels: documentation

#26 :recycle: added GA to config file
  website/siteConfig.js
Labels: enhancement

#27 :recycle: minor amends
  website/pages/en/index.js
Labels: enhancement

#28 Taimoor/amend
  docs/react-commons-collection.md
  docs/react-icon-collection.md
  docs/react-logo-collection.md
  docs/react-ui-collection.md
Labels: enhancement
