Repository react-pakistan/react-pakistan-docs, pull requests merged in 2020-10, with the labels that each got.

#55 :recycle: minor amends
  docs/intro.md
  website/package.json
  website/pages/en/index.js
  website/pages/en/users.js
  website/yarn.lock
Labels: dependencies, enhancement

#52 all the tags updated with the storybook react common library
  docs/react-commons-collection.md
Labels: documentation

#56 Taimoor/amemd
  docs/react-commons-collection.md
  docs/react-docs-contributors.md
  docs/react-emoji-collection.md
  docs/react-native-emoji-collection.md
  docs/react-native-icon-collection.md
  docs/react-native-logo-collection.md
  website/i18n/en.json
  website/sidebars.json
  yarn.lock
Labels: enhancement

#53 React ui collection dawood
  docs/react-ui-collection.md
  website/pages/en/index.js
Labels: documentation

#57 :pencil2: updated README
  website/README.md
Labels: dependencies

#58 Taimoor/amend
  package.json
  website/README.md
  website/i18n/en.json
  website/package.json
  website/pages/en/index.js
  website/pages/en/users.js
  website/sidebars.json
  website/siteConfig.js
  website/yarn.lock
Labels: dependencies, enhancement

#59 Taimoor/amend
  blog/2020-11-20-storybook-sitemap.md
  docs/intro.mdx
  src/feature.js
  src/pages/index.js
  static/img/react-pakistan-architecture.svg
  yarn.lock
Labels: dependencies, enhancement

#60 Taimoor/amend
  docs/doc2.md
  docs/doc3.md
  docs/intro.md
  docs/intro.mdx
  docs/mdx.md
  docs/react-commons-collection.mdx
  docs/react-emoji-collection.mdx
  docs/react-icon-collection.mdx
  docs/react-logo-collection.mdx
  docs/react-native-boilerplate-contributors.mdx
  docs/react-native-boilerplate.mdx
  docs/react-native-commons-collection.mdx
  docs/react-native-commons-contributors.mdx
  docs/react-native-emoji-collection.mdx
  docs/react-native-emoji-contributors.mdx
  docs/react-native-icon-collection.mdx
  docs/react-native-icon-contributors.mdx
  docs/react-native-logo-collection.mdx
  docs/react-native-logo-contributors.mdx
  docs/react-native-ui-collection.mdx
  docs/react-native-ui-contributors.mdx
  docs/react-ui-collection.mdx
  sidebars.js
Labels: dependencies, enhancement

#61 Taimoor/blog
  blog/2020-11-16-welcome.md
  blog/2020-11-20-storybook-sitemap.md
Labels: dependencies, enhancement
